INSERT INTO COMMUNITY_MEMBER (ID, ENTRY_DATE, FIELD_OF_EXPERTISE, FIRSTNAME, LASTNAME) VALUES (1, '2021-12-06', 'Java', 'Samwise', 'Gamgee');

INSERT INTO COMMUNITY_MEMBER (ID, ENTRY_DATE, FIELD_OF_EXPERTISE, FIRSTNAME, LASTNAME) VALUES (2, '1021-12-06', 'Black Magic', 'Mithrandir', 'Olorin');

INSERT INTO COMMUNITY_MEMBER (ID, ENTRY_DATE, FIELD_OF_EXPERTISE, FIRSTNAME, LASTNAME) VALUES (3, '1870-12-06', 'Immortal Mortal', 'Aragon', 'Elvenstar');

INSERT INTO COMMUNITY_MEMBER (ID, ENTRY_DATE, FIELD_OF_EXPERTISE, FIRSTNAME, LASTNAME) VALUES (4, '1870-12-06', 'Same first and lastname', 'Legolas', 'Greenleave');